# application.yaml

spring:
  application:
    name: WeatherFit
  profiles:
    include: secure

  # --- AI SETTINGS ---
  ai:
    openai:
      chat:
        options:
          model: ${OPENAI_MODEL}    # 기본값: gpt-5
          temperature: ${OPENAI_TEMPERATURE}    # 기본값: 1.0

  # --- DATABASE CONNECTION SETTINGS ---
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:${DB_PORT}/weather_fit    # 기본값: 3306
    username: ${DB_USERNAME}    # 기본값: root
    password: ${DB_PASSWORD}    # 기본값: 1234

  # --- JPA/HIBERNATE SETTINGS ---
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        # JPA가 실행하는 모든 SQL 쿼리를 콘솔 로그에 출력해주는 기능
        show_sql: true
        # show_sql: true 설정으로 출력되는 SQL 쿼리에 줄 바꿈과 적절한 들여쓰기를 추가하여 가독성을 높여주는 기능
        format_sql: true
