# application.yaml

spring:
  application:
    name: WeatherFit
  profiles:
    include: secure

  # --- AI SETTINGS ---
  ai:
    openai:
      chat:
        options:
          model: ${OPENAI_MODEL}    # 기본값: gpt-5
          temperature: ${OPENAI_TEMPERATURE}    # 기본값: 1.0

  # --- DATABASE CONNECTION SETTINGS ---
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:${DB_PORT}/weather_fit    # 기본값: 3306
    username: ${DB_USERNAME}    # 기본값: root
    password: ${DB_PASSWORD}    # 기본값: 1234

  # --- JPA/HIBERNATE SETTINGS ---
  jpa:
    properties:
      hibernate:
        # JPA가 실행하는 모든 SQL 쿼리를 콘솔 로그에 출력해주는 기능
        show_sql: true
        # show_sql: true 설정으로 출력되는 SQL 쿼리에 줄 바꿈과 적절한 들여쓰기를 추가하여 가독성을 높여주는 기능
        format_sql: true

# --- 날씨 API ---
weather:
  kma:
    key: ${KMA_API_KEY}
  open-weather:
    key: ${OPEN_WEATHER_API_KEY}

# --- 카카오 지도 API ---
kakao:
  api:
    key: ${KAKAO_API_KEY}

# JWT (JSON Web Token) 설정
jwt:
  # 토큰을 서명할 때 사용할 Secret Key
  secret: ${JWT_SECRET_KEY}

  # 토큰 만료 시간 설정 (단위: 밀리초)
  # Access Token: 짧게 설정 (30분)
  # access-token-expiration-ms: 1800000
  # Test 용
  access-token-expiration-ms: 10000

  # Refresh Token: 길게 설정 (7일)
  refresh-token-expiration-ms: 604800000

# 파일 업로드 경로 설정
upload:
  path: uploads/