spring:
  application:
    name: WeatherFit
  #--- DATABASE CONNECTION SETTINGS ---
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/weather_fit
    username: root
    password: 1234

  #--- JPA/HIBERNATE SETTINGS ---
  jpa:
    properties:
      hibernate:
        # JPA가 실행하는 모든 SQL 쿼리를 콘솔 로그에 출력해주는 기능
        show_sql: true
        # show_sql: true 설정으로 출력되는 SQL 쿼리에 줄 바꿈과 적절한 들여쓰기를 추가하여 가독성을 높여주는 기능
        format_sql: true